### ISSUE TITLE
Get PAT

### ISSUE THREAD

**Issue by BastianZim** [BastianZim/test-labeler#12]
For staged-recipes, we'll have to ask CF core if we can use one of the bots for this.

_Originally posted by @BastianZim in https://github.com/BastianZim/test-labeler/issues/1#issuecomment-1065004475_

We believe a personal access token is needed with the following rights:

* repo / public_repo
* admin:org / read:org

This is needed to check for team membership.

Ref: https://github.com/BastianZim/test-labeler/blob/b5e194888580909903aff4eb121b6cfd1c13ace7/.github/workflows/automate-review-labels.yml#L81

**Comment by BastianZim** [comment]
@carterbox I added the token that's available in the staged-recipes repo now after asking core but it's failing. Can you see any issues?

Workflow: https://github.com/conda-forge/staged-recipes/blob/db84d8a66b2d48187d7fc22e9d5a58f63935d59c/.github/workflows/automate-review-labels.yml#L78

Docs: https://github.com/actions/github-script#using-a-separate-github-token

Logs: https://github.com/conda-forge/staged-recipes/actions/runs/1982049684

**Comment by carterbox** [comment]
Let's see if it's still working tomorrow. Maybe it just took a while for the secret to propagate to the workers?

**Comment by BastianZim** [comment]
Still not working: https://github.com/conda-forge/staged-recipes/runs/5543442584?check_suite_focus=true

**Comment by carterbox** [comment]
Yeah, it's weird because we definitely are providing that key:

https://github.com/conda-forge/staged-recipes/blob/e4241a2795e61e05657cea36a91ffcad306ee228/.github/workflows/automate-review-labels.yml#L79

**Comment by BastianZim** [comment]
I'll open an issue at the scripts repo because we are doing everything correctly, from what I can see. The secret is also formatted the same way it is in https://github.com/conda-forge/staged-recipes/blob/e4241a2795e61e05657cea36a91ffcad306ee228/.github/workflows/create_feedstocks.yml#L58 and there it's working.

**Comment by BastianZim** [comment]
Issue in https://github.com/actions/github-script/issues/248

**Comment by BastianZim** [comment]
Seems like this was because it's from a fork: https://github.com/actions/github-script/issues/248#issuecomment-1068270200

I haven't investigated this but maybe we can use https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by carterbox** [comment]
But all of our PRs are from a fork! 😆 🤦🏼 

What we want to do is check the identity of a person when they submit a review. However, the closest thing we have to that trigger would be:

```yaml
on:
  pull_request_target:
    types: [review_request_removed] 
```

I don't think this is the correct trigger. I couldn't find docs, but I think this means "when the PR author retracts their review request not when a review is submitted".

Since, it doesn't seem like we can use Actions with elevated privilege to check the identity of reviewers from forks, I think we need to rebuild our actions to use the *built-in* review-request functionality instead of trying to recreate it using labels.

Something like:

```mermaid
sequenceDiagram
    actor User
    participant issue
    participant GitHub actions
    actor Reviewer
    User->>issue: Adds any comment
    activate GitHub actions
    alt is PR AND no review-requested label exists
        loop Over ['@conda-forge/staged-recipes', '@conda-forge/help-python', '@conda-forge/help-python-c', '@conda-forge/help-r', '@conda-forge/help-java', '@conda-forge/help-nodejs', '@conda-forge/help-c-cpp', '@conda-forge/help-perl', '@conda-forge/help-julia', '@conda-forge/help-ruby']
            alt team is in comment
                GitHub actions->>issue: Adds review-requested label
                GitHub actions->>issue: Adds team label
                GitHub actions->>issue: Remove Awaiting author contribution label
                GitHub actions-->>issue: Assigns team for review
            end
        end
    end
    deactivate GitHub actions
    Reviewer->>issue: Submits review
    activate GitHub actions
    alt review submitted on behalf of conda-forge team OR team review request fulfilled
       GitHub actions->>issue: Remove review-requested label
       GitHub actions->>issue: Add Awaiting author contribution label
    end
    deactivate GitHub actions
```

There's gotta be a way to check if a review request was submitted on behalf of a team without special authentication because this is public info, right? When you request review from a team, the review is automatically cleared if someone from that team reviews?

**Comment by BastianZim** [comment]
> But all of our PRs are from a fork! 😆 🤦🏼

Yeah....

I think we can use `pull_request_target`.  That is run from the base, meaning it has access to the secrets and should have the same trigger. The trigger you mentioned works as well but I don't think that we actually need to use a different conditional. We should just need to change `pull_request` to `pull_request_target`. I'll make a PR for that later here.

> There's gotta be a way to check if a review request was submitted on behalf of a team without special authentication because this is public info, right?

Unfortunately not, from what I can see. If you visit https://github.com/orgs/conda-forge/teams/staged-recipes without being logged in you won't see anything. You need to be logged in and have the necessary rights to see that.

**Comment by carterbox** [comment]
> We should just need to change pull_request to pull_request_target

[None of these are `pull_request`](https://github.com/conda-forge/staged-recipes/blob/a0ca0a383a4b7d34a21c779cf543568230a3167e/.github/workflows/automate-review-labels.yml#L3-L9), so none can be changed to `pull_request_target`. Unless `pull_request_review_target` or `pull_request_review_comment_target` exist?
> > There's gotta be a way to check if a review request was submitted on behalf of a team without special authentication because this is public info, right?
>
> Unfortunately not, from what I can see. 

I meant that whether the PR has been review by a team is public info? For example, [on this pr](https://github.com/conda-forge/staged-recipes/pull/18316#partial-pull-merging) the public can see that you are listed in the "Reviewers" section on the right panel with a green check mark. So if the name of a team is in the "Reviewers" section, then we can monitor whether someone from the team has reviewed even if we can't monitor who is on the team because either the team name will disappear or get a green check mark.

**Comment by carterbox** [comment]
![Screenshot from 2022-03-15 20-27-42](https://user-images.githubusercontent.com/9604511/158500344-3fae29b6-1581-4d36-b983-a588e67a4b8d.png)

For example: https://github.com/conda-forge/staged-recipes/pull/18187#pullrequestreview-911005299 The public can see that someone from this help-python has not yet reviewed since I added this review request.

**Comment by carterbox** [comment]
The public cannot see who reviewed on behalf of a team, but when someone does review on behalf of the team, the team name is removed from the "Reviewers" section. I think we can use that removal event for our purposes.

**Comment by carterbox** [comment]
>  like most use a GitHub bot for this 

Oh. The difference with a bot is that it always has the key regardless of whether the PR is from a fork because the bot's code is separate from the repo of the PR?

**Comment by BastianZim** [comment]
https://www.geeksforgeeks.org/making-a-github-bot/

Yes, the permissions are explicitly given and don't depend on where the bot runs.

The problem is that creating a bot is a much bigger project than creating some GitHub actions...

**Comment by BastianZim** [comment]
Also, the bot needs to be deployed on a server, which conda-forge doesn't have.

**Comment by carterbox** [comment]
I implemented a version of the tagging system that doesn't require a PAT, but it does require that the PRs have team reviews requested. Also, technically, I didn't fully test it because we don't have teams on the test repo. Please take a look.

**Comment by BastianZim** [comment]
Have had a look now - looks great! 

I will try a dry run tomorrow when I'm back at my computer but I think we should just wait for a calm moment and test it in staged-recipes. Matthew said we can, as long as it's not too distracting.

**Comment by BastianZim** [comment]
Closing it because of new approach
